# Datenbankkonfiguration für das Report-System
database:
  enabled: false #if set to false the plugin will create a local json file to log reports
  host: ""
  port: 3306 #default mysql port
  name: ""
  username: ""
  password: ""

# RankPointsAPI Konfiguration
rankpointsapi:
  integration: true
  host: ""
  port: 3306 #default mysql port
  name: ""
  username: ""
  password: ""
  check-interval: 10 # Seconds between RankPoints database queries

discord-bot-token: ""
discord-channel-id-reports: ""
discord-channel-id-notifications: ""

# Report-Einstellungen
report:
  cooldown-seconds: 300 # Zeitfenster in Sekunden, in dem Meldungen begrenzt werden
  max-reports-per-interval: 2 # Maximale Anzahl an Meldungen pro Spieler innerhalb des Zeitfensters
