# Datenbankkonfiguration für das Report-System
database:
  enabled: false
  host: ""
  port: 3306
  name: ""
  username: ""
  password: ""

# RankPointsAPI Konfiguration
rankpointsapi:
  integration: true
  host: ""
  port: 3306
  name: ""
  username: ""
  password: ""

discord-bot-token: ""
discord-channel-id-reports: ""
discord-channel-id-notifications: ""
