name: AkzuwoExtension
version: '${project.version}'
main: ch.ksrminecraft.akzuwoextension.AkzuwoExtension
api-version: '1.20'
commands:
  report:
    description: Report a player.
    usage: /report <player> <reason>
  viewreports:
    description: View all reports.
    usage: /viewreports
  viewreportsgui:
    description: View all reports in a GUI.
    usage: /viewreportsgui
  deletereport:
    description: Delete a report by ID.
    usage: /deletereport <id>
  akzuwoextension:
    description: Base command for confirmations.
    usage: /akzuwoextension confirm

tutorialcommand: true


softdepend: [PlaceholderAPI]



permissions:
  akzuwoextension.staff:
    description: Allows staff members to manage and review player reports.
    default: op
  akzuwoextension.exempt:
    description: Prevents a player from being reported by others.
    default: false

